theme: jekyll-theme-hacker
title: Robert McAtee
description: Division Chief, Hosting Services, Administrative Office of the U.S. Courts âš–ï¸ Empowering People âš¡ Federal Courts Software Factory ğŸ­ Software Engineer ğŸ“
github:
  is_project_page: false
