theme: jekyll-theme-hacker
title: Robert McAtee
description: IT Director @ U.S. Federal Judiciary ğŸŒŸ Delivering Solutions that Improve the Way People Work ğŸ­ Founder of Federal Courts Software Factory ğŸ“ Software Engineer
github:
  is_project_page: false
