theme: jekyll-theme-hacker
title: Robert McAtee
description: Division Chief, Hosting Services â˜ï¸ Administrative Office of the U.S. Courts âš–ï¸ Federal Courts Software Factory ğŸ­ Software Engineer ğŸ“
github:
  is_project_page: false
