theme: jekyll-theme-hacker
title: Robert McAtee
description: âš–ï¸ IT Director, U.S. Federal Judiciary ğŸŒŸ Empowering People ğŸ­ Federal Courts Software Factory ğŸ“ Software Engineer
github:
  is_project_page: false
